image: atlassian/default-image:3

pipelines:
    default:
        - step:
              name: Build and Push to ECR
              script:
                  # 1. Define Variables
                  - IMAGE_NAME=magento-api-platform
                  - AWS_REGION=eu-central-1
                  - REPOSITORY_URL=801404438871.dkr.ecr.eu-central-1.amazonaws.com
                  - REPOSITORY_URL_PREFIX=sunday
                  
                  # 2. Install Dependencies
                  - apt-get update && apt-get install -y awscli docker
                  
                  # 3. Configure AWS Credentials
                  # Make sure AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are set in Bitbucket Repository Variables
                  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
                  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
                  - aws configure set region $AWS_REGION
                  
                  # 4. Authenticate Docker with ECR
                  - $(aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URL)
                  
                  # 5. Build Docker Image
                  - docker build -t $IMAGE_NAME .
                  
                  # 6. Tag Docker Image
                  - docker tag $IMAGE_NAME:latest $REPOSITORY_URL/$REPOSITORY_URL_PREFIX/$IMAGE_NAME:latest
                  
                  # 7. Push Docker Image to ECR
                  - docker push $REPOSITORY_URL/$REPOSITORY_URL_PREFIX/$IMAGE_NAME:latest
